// ======================================================
// ResumeSuggestions.jsx
// SkillSync V2
// AI Resume Suggestions
// ======================================================

import {
  Lightbulb,
  CheckCircle,
  AlertTriangle,
} from "lucide-react";

/*
========================================================

Purpose

Displays AI-generated resume improvement suggestions.

Features

✔ Suggestion Cards
✔ Success Message
✔ Icons
✔ Better UI
✔ Professional Layout

========================================================
*/

function ResumeSuggestions({ suggestions }) {

  if (!suggestions) return null;

  return (

    <div className="mt-14">

      {/* ===================================== */}
      {/* Heading */}
      {/* ===================================== */}

      <div className="flex items-center gap-3 mb-8">

        <Lightbulb
          className="text-yellow-400"
          size={30}
        />

        <div>

          <h2 className="text-3xl font-bold">

            AI Resume Suggestions

          </h2>

          <p className="text-gray-400 mt-1">

            Smart recommendations to improve your resume.

          </p>

        </div>

      </div>

      {/* ===================================== */}
      {/* No Suggestions */}
      {/* ===================================== */}

      {suggestions.length === 0 ? (

        <div className="bg-green-500/10 border border-green-500 rounded-2xl p-6 flex items-center gap-4">

          <CheckCircle
            className="text-green-400"
            size={30}
          />

          <div>

            <h3 className="text-xl font-bold text-green-400">

              Excellent Resume!

            </h3>

            <p className="text-gray-300 mt-2">

              Your resume looks strong. Keep improving your
              projects and interview preparation.

            </p>

          </div>

        </div>

      ) : (

        <>
          {/* ===================================== */}
          {/* Summary */}
          {/* ===================================== */}

          <div className="bg-slate-800 rounded-2xl border border-slate-700 p-5 mb-6">

            <p className="text-gray-300">

              <span className="font-bold text-cyan-400">

                {suggestions.length}

              </span>{" "}

              improvement suggestion(s) generated by AI.

            </p>

          </div>

          {/* ===================================== */}
          {/* Suggestion Cards */}
          {/* ===================================== */}

          <div className="grid md:grid-cols-2 gap-5">

            {suggestions.map((item, index) => (

              <div
                key={index}
                className="bg-yellow-500/10 border border-yellow-500 rounded-2xl p-5 hover:border-yellow-400 transition-all duration-300"
              >

                <div className="flex items-start gap-4">

                  <AlertTriangle
                    className="text-yellow-400 mt-1"
                    size={24}
                  />

                  <div>

                    <h3 className="font-bold text-yellow-300">

                      Suggestion #{index + 1}

                    </h3>

                    <p className="text-gray-300 mt-2 leading-7">

                      {item}

                    </p>

                  </div>

                </div>

              </div>

            ))}

          </div>

        </>

      )}

    </div>

  );

}

export default ResumeSuggestions;